name: pi-pulse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - shiny
  - plotly
  - python-dotenv
  - httpx
  - pandas
  - pyyaml
  - pip:
    - shinyswatch
    - faicons
    - shinywidgets
