name: pi-pulse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - shiny
  - plotly
  - httpx
  - pandas
  - pyyaml
  - fastapi
  - psutil
  - uvicorn
  - pip:
    - shinyswatch
    - faicons
    - shinywidgets
    - sensirion-driver-adapters
    - sensirion-i2c-driver
    - sensirion-i2c-sen66
