relay_base_url: http://127.0.0.1:8010

devices:
  "10":
    label: "RPi4 (192.168.121.10)"
    pulse: {}

  "11":
    label: "RPi4 (192.168.121.11)"
    pulse: {}
    sen66: {}
    h10:
      "EA78562C": {}

  "pixel-7":
    label: "Pixel 7 (100.81.55.124)"
    pulse:
      metrics:
        temp:
          field: thermal_headroom
          label: Thermal Headroom
          unit: null
    gps: {}
    h10:
      "6FFF5628": {}
    pacer:
      "DA2E2324": {}
